name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Publish Docker
  # uses: elgohr/Publish-Docker-Github-Action@93655185f260b851ede78d9a57760a8bbda65f68
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_names: true
    # The name of the image you would like to push
        name: hjin/chrome-node
    # Set the default branch of your repository (default: master)
        default_branch: main
    # Use workdir when you would like to change the directory for building
        workdir: ./chrome-node


